import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Credix Full-Stack Technical Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center h-screen p-32">
        <h1 className="capitalize">credix full-stack technical task</h1>
        <p>
          This is the frontend skeleton project for the Credix full-stack
          technical task.
        </p>
        <p>Feel free to modify this project and add your own content.</p>
      </main>

      <footer className="flex justify-center items-center py-8 border-t border-gray-200">
        <a
          href="https://credix.finance"
          target="_blank"
          rel="noopener noreferrer"
        >
          Credix
        </a>
      </footer>
    </div>
  );
};

export default Home;
